### ISSUE TITLE
Upload latest Docker image for Payara Server 181 (4.1.2.181) to Docker Hub

### ISSUE THREAD

**Issue by larslorenzen** [payara/docker-payaraserver-full#30]
Hi,
Can you please upload the Docker image tag for Payara Server 181 (4.1.2.181) to Docker Hub.

Also for the micro payara please :)

**Comment by mikecroft** [comment]
All queued up to be built now! Should be done in a few minutes from now.

These 4.x releases all still have the `181` tag; when Payara 5 is released, it will be `5.181`, so users will get the same 4.x branch by default for the 181 cycle, then future tags will go back to just `182`, `183` etc since we'll retain just the one public "current" build of Payara Server and Micro.

**Comment by fredgate** [comment]
So there is no image for the payara full 4 182 ?
It's annoying as variable reference for JVM options is only available since Payara Server 4.1.2.182 and 5.182 : https://docs.payara.fish/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html
I will need this feature for an existing application not compatible with payara 5.

**Comment by smillidge** [comment]
4.182 is a customer only release as Payara 4 is in maintenance. It is available through a support contract.

**Comment by fredgate** [comment]
Thank you for the answer.
