### ISSUE TITLE
Restarting the domain to apply a configuration change stops the container

### ISSUE THREAD

**Issue by paulnuk** [payara/docker-payaraserver-full#45]
**Replicate as follows:**

Start a container from the image
`docker run -d --name payarafull payara/server-full`

bash into the image
`docker exec -u 0 -it payarafull bash`

Go into asadmin

Make a configuration change that requires a restart
`set server.thread-pools.thread-pool.http-thread-pool.max-thread-pool-size=8`

restart the domain to get the change applied
`restart-domain domain1`

**Expected behaviour:**

The domain restarts with the changes applied

**Actual behaviour**

The domain stops so the entrypoint exits and therefore the container stops

**Comment by MattGill98** [comment]
Hi @paulnuk,

Once the `startInForeground.sh` script is started with the default `CMD` command, restarting the server cannot be performed. This can however be achieved by overriding the `CMD` options since https://github.com/payara/docker-payaraserver-full/pull/59. I'll close this issue, although feel free to reopen it if you have any issues.

Kind regards,

Matt
