### ISSUE TITLE
Upload latest Docker image for Payara Server 183 (4.1.2.183) to Docker Hub

### ISSUE THREAD

**Issue by Sonnenhut** [payara/docker-payaraserver-full#57]
Hi,

could you please upload the version 4.183 to Docker hub?
Currently the 5.183 is available, but not the 4.183.

Also the 4.182 is missing.

Cheers!

**Comment by OndrejM** [comment]
Hi, since the version of 5.181 was released, Payara opensource project doesn't support community versions of Payara 4.x. The latest community build of Payara 4.x is 4.181, together with a docker image. For paying subscribers of Payara Enterprise service, there are new builds of Payara 4.x available, like 4.182 and 4.183. To get those builds and docker images, you would need to become a subscriber of the Payara Enterprise service and request the docker images.
