### ISSUE TITLE
docker run --init

### ISSUE THREAD

**Issue by AllenConquest** [payara/docker-payaraserver-full#80]
In my version of the Dockerfile I don't use tini, I just use the docker run option of --init, which does the same thing. It saves installing yet another utility in the docker image, when Docker comes with it built in. I'm not even using the latest version of docker, so I think this is quite an old option. 

Would it be worth removing tini and updating the readme to show the preferred way of running the image?

**Comment by MattGill98** [comment]
Hi @AllenConquest,

We initially discussed this and although it's possible, we want to make sure that the container works without that much of an intimate knowledge of Docker. Running without `--init` makes the container simpler to use. Because of this, our preference is to keep tini in.

I'll close this issue, although if you have any questions feel free to reopen it!

Kind regards,

Matt
